{% set name = "mne-gui-addons" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mne-gui-addons-{{ version }}.tar.gz
  sha256: 0f5231065e823f051d9df09077b866cf27bda91a4582b280dfeaa725550c4ab7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - packaging
    - qtpy
    - pyqt
    - pyvista
    - pyvistaqt
    - vtk
    - matplotlib-base
    - mne-base
    - nibabel
    - dipy >=1.4
    - traitlets
    - setuptools >=65

test:
  imports:
    # VTK import is broken on Windows so don't try to import there
    - mne_gui_addons  # [not win]
  commands:
    - pip check  # [not win]
  requires:
    - pip
    - setuptools

about:
  home: https://pypi.org/project/mne-gui-addons/
  summary: MNE-Python GUI addons.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - alexrockhill
